---
- name: Clone/pull grafana from github
  git: repo={{ grafana.repo }} dest={{ grafana.path }} version="{{ grafana.branch }}"
       key_file="/home/{{ grafana.user }}/.ssh/gitro_id_rsa" accept_hostkey=yes force=yes
  become_user: "{{ grafana.user }}"
  tags:
    - update
