- name: Debian | Add elasticsearch signing key
  apt_key: url="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present

- name: Debian | Get elasticsearch repository
  apt_repository: repo="deb http://packages.elasticsearch.org/elasticsearch/2.x/debian stable main"

- name: Debian | Install elasticsearch
  apt: pkg=elasticsearch state=installed
