---
- name: Enable new config
  shell: 'sudo ldconfig'

- name: Make that webtelemetry user is owner of virtualenv
  file:
    path: "{{ virtualenv_path }}"
    state: directory
    owner: {{ product.admin }}
    group: wtgroup
    recurse: yes

- name: Upgrade pip
  shell: "{{ virtualenv_path }}/bin/pip install --upgrade pip"
  environment: "{{ env_vars }}"
  become_user: "{{ product.user }}"

- name: Upgrade setuptools
  shell: "{{ virtualenv_path }}/bin/pip install --upgrade setuptools"
  environment: "{{ env_vars }}"
  become_user: "{{ product.user }}"

- name: Install {{ product.name }}
  pip: name=telemetrix-core{{ wt_core.version }}
       extra_args="--upgrade --extra-index-url {{ gemfury_url }}"
       virtualenv="{{ virtualenv_path }}"
  environment: "{{ env_vars }}"
  become_user: "{{ product.user }}"

- name: Install python dependencies (telemetrix-core)
  shell: cat {{ virtualenv_path }}/wt_config/telemetrix-core/requirements.txt | xargs -L 1 {{ virtualenv_path }}/bin/pip install --extra-index-url {{ gemfury_url }}
  environment: "{{ env_vars }}"
  become_user: "{{ product.user }}"
