# Configure Using Gemfile
# gem 'activerecord-jdbc-postgresql-adapter'
#
development:
  adapter: jdbc-postgresql
  encoding: utf8
  database: {{ product.db.dev_name }}
  username: root
  password: {{ product.db.dev_password }}

test:
  adapter: jdbc-postgresql
  encoding: utf8
  database: {{ product.db.test_name }}
  username: root
  password: {{ product.db.test_password }}

production:
  adapter: jdbc-postgresql
  encoding: utf8
  database: {{ product.db.name }}
  username: {{ product.db.user }}
  password: {{ product.db.pass }}
  host: {{ product.db.host }}

# ---- Report databases ----

dashboard_development:
  adapter: jdbc-postgresql
  encoding: utf8
  database: {{ product_db_name }}
  username: {{ product_db_user }}
  password: {{ product_db_pass }}
  host: {{ product.db.host }}

dashboard_test:
  adapter: jdbc-postgresql
  encoding: utf8
  database: {{ product.db.name }}
  username: root
  password: {{ product.db.password }}

dashboard_production:
  adapter: jdbc-postgresql
  encoding: utf8
  database: {{ product_db_name }}
  username: {{ product_db_user }}
  password: {{ product_db_pass }}
  host: {{ product.db.host }}
