---
- name: Remove context.xml
  file: path=/WT/appserver/conf/context.xml state=absent

- name: Create context.xml
  template: src=context.xml.j2 dest=/WT/appserver/conf/context.xml
  become_user: "{{ product.user }}"

- name: Create configs directory
  file: path=/WT/configs state=directory owner=wtuser group={{ product.admin }}

- name: Create config/settings directory
  file: path=/WT/configs/settings state=directory owner=wtuser group={{ product.admin }}

- name: Copy tenant files
  copy: src="{{ item }}.yml" dest="/WT/configs/settings/{{ item }}.yml" owner=wtuser group={{ product.admin }}
  with_items: '{{ snmp.tenants }}'

- name: Create database.yml
  template: src=database-jruby.yml.j2 dest=/WT/configs/database.yml
  become_user: "{{ product.user }}"

- name: Update settings.local.yml
  template: src=settings-jruby.yml.j2 dest=/WT/configs/settings.local.yml owner=wtuser group="{{ grafana.group }}"
  become_user: "{{ product.user }}"

- name: Update Basalt.yml
  template: src=Basalt.yml.j2 dest=/WT/configs/Basalt.yml owner=wtuser group="{{ grafana.group }}"
  become_user: "{{ product.user }}"

- name: Stat database.yml
  stat: path=/WT/appserver/webapps/snmp/WEB-INF/config/database.yml
  register: database
  changed_when: true

- name: Remove database.yml
  command: rm /WT/appserver/webapps/snmp/WEB-INF/config/database.yml
  when: database.stat.exists

- name: Create symlink for database.yml
  file: src=/WT/configs/database.yml dest=/WT/appserver/webapps/snmp/WEB-INF/config/database.yml
  args:
    owner: {{ product.admin }}
    group: {{ product.admin }}
    state: link
    force: yes

- name: Create symlink for settings.local.yml
  file: src=/WT/configs/settings.local.yml dest=/WT/appserver/webapps/snmp/WEB-INF/config/settings.local.yml
  args:
    owner: {{ product.admin }}
    group: {{ product.admin }}
    state: link
    force: yes

- name: Create symlink for Basalt.yml
  file: src=/WT/configs/Basalt.yml dest=/WT/shared/Basalt.yml
  args:
    owner: {{ product.admin }}
    group: {{ product.admin }}
    state: link
    force: yes

- name: Create symlink for Basalt.yml
  file: src=/WT/configs/Basalt.yml dest=/WT/appserver/webapps/snmp/shared/Basalt.yml
  args:
    owner: {{ product.admin }}
    group: {{ product.admin }}
    state: link
    force: yes

- name: Remove bundled configs
  file: path=/WT/appserver/webapps/snmp/WEB-INF/config/settings
  args:
    state: absent

- name: Create symlink for tenant settings
  file: src=/WT/configs/settings dest=/WT/appserver/webapps/snmp/WEB-INF/config/settings
  args:
    owner: {{ product.admin }}
    group: {{ product.admin }}
    state: link
    force: yes

- name: Create tomcat.conf
  template: src=tomcat.conf.j2 dest=/etc/init/tomcat.conf

- name: Create log directory
  file: dest=/WT/logs
  args:
    owner: {{ product.admin }}
    group: {{ product.admin }}
    state: directory

- name: Touch grafana log
  file: dest=/WT/logs/grafana.log
  args:
    owner: {{ product.admin }}
    group: {{ product.admin }}
    state: touch
