---
# Reboot host
- name: rebooting host ansible_ssh_host
  shell: sleep && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
  sudo: yes

- name: waiting for host ansible_ssh_host to come back
  local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 delay=10 timeout=30
  sudo: false