- name: Install setuptools
  yum: name=python-setuptools state=present

- name: Install PIP
  easy_install: name=pip

- name: Install Global Python packages
  pip:  name={{ item }}
  with_items:
    - virtualenv
    - virtualenvwrapper
    - pyaml

# - name: Check python version
#   shell: python --version
#   register: python_ver
#
# - name: Install the 'Development tools' package group
#   yum: name="@Development tools" state=present
#   when: "'{{ python_version }}' not in python_ver.stderr"
#
# - name: Install dependencies
#   yum: name="{{ item }}" state=present
#   with_items:
#     - zlib-devel
#     - bzip2-devel
#     - openssl-devel
#     - ncurses-devel
#     - readline-devel
#     - pcre-devel
#     - curl-devel
#     - sqlite-devel
#   when: "'{{ python_version }}' not in python_ver.stderr"
#
# - name: Unarchive python from source
#   unarchive: src="Python-{{ python_version }}.tgz" dest=/usr/local/src/
#   when: "'{{ python_version }}' not in python_ver.stderr"
#   tags:
#     - python
#
# - name: Run Configure for build
#   shell: ./configure --with-threads --enable-shared --enable-unicode=ucs4
#   args:
#     chdir: "/usr/local/src/Python-{{ python_version }}"
#     executable: /bin/bash
#   when: "'{{ python_version }}' not in python_ver.stderr"
#   tags:
#     - python
#
# - name: Run make
#   shell: make
#   args:
#     chdir: "/usr/local/src/Python-{{ python_version }}"
#     executable: /bin/bash
#   when: "'{{ python_version }}' not in python_ver.stderr"
#   tags:
#     - python
#
# - name: Run make install
#   shell: make install
#   args:
#     chdir: "/usr/local/src/Python-{{ python_version }}"
#     executable: /bin/bash
#   when: "'{{ python_version }}' not in python_ver.stderr"
#   tags:
#     - python
#
# - name: Touch local-lib.conf
#   file: path=/etc/ld.so.conf.d/local-lib.conf state=touch
#   when: "'{{ python_version }}' not in python_ver.stderr"
#   tags:
#     - python
#
# - name: Add /usr/local/lib line to local-lib.conf
#   lineinfile: dest=/etc/ld.so.conf.d/local-lib.conf line="/usr/local/lib"
#   when: "'{{ python_version }}' not in python_ver.stderr"
#   tags:
#     - python
#
# - name: Run ldconfig
#   command: /usr/sbin/ldconfig
#   when: "'{{ python_version }}' not in python_ver.stderr"
#   tags:
#     - python
#
#
# - name: Check if setuptools is already installed
#   stat: path=/usr/local/bin/easy_install-2.7
#   register: setuptools
#
# - name: Install Setuptools
#   yum: name=python-setuptools state=present
#   when: not setuptools.stat.exists
#
# - name: Check if pip is already installed
#   stat: path=/usr/local/bin/pip2.7
#   register: pip
#
# - name: Install PIP
#   easy_install: name=pip
#   when: not pip.stat.exists
