#!/bin/bash
account=$1

### Add Account info below ###
function bdes()
{
    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=""
    AWS_ACCOUNT=WebTelemetry-bdes
}

function dev()
{
    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=""
    AWS_ACCOUNT=WebTelemetryDev
}

function ssn()
{
    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=""
    AWS_ACCOUNT=WebTelemetry-ssn
}

function prospects()
{
    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=""
    AWS_ACCOUNT=WebTelemetry-Prospects
}

function webtelemetry()
{
    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=""
    AWS_ACCOUNT=WebTelemetry-Prospects
}

function wt_go()
{
    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=""
    AWS_ACCOUNT=WebTelemetry
}

function gridspice()
{
    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=""
    AWS_ACCOUNT=GridSpice
}


##############################

if [ $0 != "-bash" ]; then
    _botoargs=$(grep "^function " $0 | sed -e 's/^function //' | sed -e 's/()//')
fi

__help() {
    if [ $0 != "-bash" ]; then
        echo "Available Options: "
        echo "$_botoargs"
    else
        echo "Help not available when sourcing."
    fi
}


if [ $account ]; then
    case $account in
        'help') __help
                ;;
        'CLEAR') unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_ACCOUNT
                 ;;
        *)  echo "Activating AWS acct: $account"
            $account && export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_ACCOUNT || echo "Error: unknown account '$account'"
            ;;
    esac
else
    echo "USAGE: source WTboto_activate <acct_func>"
fi


## unset functions from typeset views##
unset __help
if [[ $_botoargs ]]; then
    unset $_botoargs
fi
