- name: Update the hostname via command
  hostname:
    name: "{{inventory_hostname_short}}"

- name: Update /etc/hostname
  copy:
    content: "{{inventory_hostname_short}}{{'\n'}}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644

- name: Update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1"
    line: "127.0.0.1{{'\t'}}{{inventory_hostname}}{% if inventory_hostname != inventory_hostname_short %}{{'\t'}}{{inventory_hostname_short}}{% endif %}{{'\t'}}localhost"
    state: present

- name: Add members of cluster to /etc/hosts
  lineinfile: dest=/etc/hosts regexp=".*{{ item }}" line="{{ hostvars[item]['ansible_ssh_host'] }} {{ item }}" state=present
  with_items: "{{ groups[env] }}"
