---
- name: Install Fx artifact
  pip: name={{ mars.artifact }}{{ mars.version }}
       extra_args="--upgrade --no-cache-dir --extra-index-url {{ gemfury_url }}"
       virtualenv="{{ virtualenv_path }}"
  environment: "{{ env_vars }}"
  become_user: "{{ product.user }}"

- name: Install Fx python dependencies
  shell: cat {{ virtualenv_path }}/wt_config/fx-telemetrix/requirements.txt | xargs -L 1 {{ virtualenv_path }}/bin/pip install --extra-index-url {{ gemfury_url }}
  environment: "{{ env_vars }}"
  become_user: "{{ product.user }}"
