---
##This currently only works for Comcast TELEMETRIX-1.1 production- the repo is in Comcast VPC, repo needs to be updated to hold distributions
## development, test and staging
- name: Playbook Build and Publish Product War
  hosts: "vrt-jenkins-static.webtelemetry.amazon"
  sudo: true

  vars:
    branch: deploy/SaaS/grafana-1.1/grafana-2.2/prod
    version: 2.2.0

  handlers:
    - name: rbenv rehash
      shell: "/WT/.rbenv/bin/rbenv rehash executable=/bin/bash chdir=/home/webtelemetry"
      sudo_user: wtuser

  tasks:
    - name: Pull from github repo
      git: repo=ssh://git@github.com/webtelemetrytelemetrix.git dest=/WT/appserver version="{{ branch }}"
           key_file="/WT/.ssh/gitro_id_rsa" accept_hostkey=yes
      sudo_user: wtuser

    - name: Gem install bundler
      gem: name=bundler state=present executable=/WT/.rbenv/shims/gem
      sudo_user: wtuser
      register: bundler
      notify: rbenv rehash

    - name: Gem install bundle
      gem: name=bundle state=present executable=/WT/.rbenv/shims/gem
      sudo_user: wtuser
      register: bundle
      notify: rbenv rehash

    - name: Gem install activesupport
      gem: name=activesupport state=present executable=/WT/.rbenv/shims/gem
      sudo_user: wtuser
      register: activesupport
      notify: rbenv rehash

    - name: Install dependencies (bundle install)
      shell: "/WT/.rbenv/shims/bundle install"
      args:
        chdir: "/WT/jruby"
        executable: /bin/bash
      sudo_user: wtuser
      register: bundled
      notify: rbenv rehash

    - name: Build snmp war
      shell: "/WT/build_metrix_war.sh"

    - name: Create tomcat webapp directory path
      file: path=/WT/appserver/webapps state=directory recurse=yes owner=wtuser group={{ product.admin }}

    - name: Create snmp directory path
      file: path=/WT/snmp state=directory recurse=yes owner=wtuser group={{ product.admin }}

    - name: Stat war file
      stat: path=/WT/appserver/snmp.war
      register:telemetrix_stat

    - name: Move war file
      command: mv /WT/appserver/snmp.war /WT/appserver/webapps/snmp.war
      when:telemetrix_stat.stat.exists

    - name: Copy jruby folder to snmp
      command: cp -rf /WT/jruby /WT/snmp/

    - name: Remove current deb
      command: rm /WT/jruby/{{ version }}_amd64.deb
      ignore_errors: true

    - name: Create apt package
      shell: "/home/jenkins/.rbenv/shims/fpm -s dir -t deb -n 'snmp' -v '{{ version }}' /WT/appserver/webapps/snmp.war /WT/snmp/jruby"
      args:
        chdir: "/WT/jruby"
      sudo_user: wtuser

    - name: Publish to webtelemetry apt-repo
      shell: "reprepro includedeb webtelemetryapt /WT/jruby/{{ version }}_amd64.deb"
      args:
        chdir: "/var/packages/debian"