---
- name: Enable services for automatic start
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - snmpd
    - vboxadd
    - vboxadd-service
    - postfix
    - WTdb
    - WTmon
    - WTappl
    - WThttpd
  register: enable_services
  ignore_errors: true
  tags: enable_services
