---
#####################################################################################################
- name: upgrade all packages
  yum: name='*' pkg='*' state=latest update_cache=yes
  ignore_errors: true
  when: packages.upgrade == "true"
  tags: packages_upgrade