---
#####################################################################################################
- name: Remove old VBoxGuestAdditions package
  command: "bash /opt/VBoxGuestAdditions-4.2.28/uninstall.sh"
  ignore_errors: true
  delegate_to: "{{ ansible_ssh_host }}"
  when: vbox_additions.reinstall == "true" or vbox_additions.remove == "true" or vbox_additions.install is not defined
  tags: vbox_additions_remove


  #####################################################################################################
  # - name: Install new VBoxGuestAdditions rpm
  - name: Install new VBoxGuestAdditions rpm
    yum: name={{ vbox_additions.urlpath }} state=present
    ignore_errors: true
    delegate_to: "{{ ansible_ssh_host }}"
    when: vbox_additions.reinstall == "true" or vbox_additions.install == "true" or vbox_additions.install is not defined
    tags: vbox_additions_install
