---
- name: Configure selinux policy
  selinux:
    state:  "{{ selinux.config }}"
    policy: "{{ selinux.policy}}"
    type:   "{{ selinux.type}}"
  register: selinux_policy

- name: Rebooting host for selinux policies to take effect
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true
  register: reboot

- name: Waiting for {{ ansible_ssh_host }} to come back
  local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 delay=10 timeout=45
  sudo: false