---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Add sudoers users to wheel group
  user: name="{{ product.admin }}" groups=wheel append=yes state=present createhome=yes


- name: Set up authorized keys for the {{ product.admin }} user
  authorized_key: user="{{ product.admin }}" key="{{item}}"
  with_file:
    - /home/{{ product.admin }}/.ssh/id_rsa.pub