---
#####################################################################################################
# Reboot the  host
- name: restart machine
  shell: sleep 2 && shutdown -r now "Host {{ ansible_default_ipv4.address }} rebooted"
  async: 1
  poll:  0
  sudo: true
  ignore_errors: true

#####################################################################################################
# Wait for host to come back up
- name: waiting for host to come back up
  local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 delay=15 timeout=500
  sudo: false