---
product_repo_ip: 10.0.0.11
webtelemetry_home: /WT
virtualenv_path: "{{ webtelemetry_home }}/virtualenvs/telemetrix"

telemetrix:
  version: 2.3
  branch: master
  app_env: production
  path: /WT/appserver
  jruby_path: "{{ telemetrix_path }}/jruby"

######################################
######  Grafana database.yml  ##########
######################################
snmp:
  db_host:
  db_host: localhost
  db_name: wt_db
  db_user: root
  db_pass: ''

  product_db_host: localhost
  product_db_name: webtelemetry_dashboard_db
  product_db_user: root
  product_db_pass: ''

#################################
######  Basalt.yml  ##########
#################################
telemetrix:
  db_host: localhost
  db_name: telemetrix_db
  db_user: root
  db_pass: ''

  forecast_model: marsb

  demandcharge:
    num_meters_per_task: 1
    mapred_job_reuse_jvm_num_tasks: 2
    mapred_child_java_opts: -Xms200M -Xmx200M
    mapred_task_timeout_ms: 1200000

  training:
    num_meters_per_task: 1
    mapred_job_reuse_jvm_num_tasks: 2
    mapred_child_java_opts: -Xms200M -Xmx200M
    mapred_task_timeout_ms: 1200000

  evaluation:
    num_meters_per_task: 1
    mapred_job_reuse_jvm_num_tasks: 2
    mapred_child_java_opts: -Xms200M -Xmx200M
    mapred_task_timeout_ms: 1200000

  metrics:
    num_meters_per_task: 1
    mapred_job_reuse_jvm_num_tasks: 2
    mapred_child_java_opts: -Xms200M -Xmx200M
    mapred_task_timeout_ms: 1200000

  reporting:
    num_meters_per_task: 1
    mapred_job_reuse_jvm_num_tasks: 2
    mapred_child_java_opts: -Xms200M -Xmx200M
    mapred_task_timeout_ms: 1200000

nginx:
  user: influxdb_user
  pass: rabbit_password
  host: localhost

hbase:
  thriftserver_host: localhost

hadoop_zookeeper:
  hosts: localhost

hdfs:
  namenode_host: localhost

telemetrix:
  host: localhost
  user: internal_api
  pass: reduce

webtelemetry:
  host: localhost
  user: wtuser
  pass: webtelemetry_password

log:
  mode: remote
  logstash_host: logstash-analytics.dev.{{ product.url }}

#######################################
######  Grafana settings.yml  ##########
#######################################
telemetrix:
  virtualenv: /WT/virtualenvs/telemetrix

data_collection_schema_url: localhost

snmp:
  db_pool_properties:
    time_between_eviction_runs_millis: 3000000
    max_active: 10
    max_idle: 1
    initial_size: 1
    min_idle: 1
    max_wait: 10000
    remove_abandonded_timeout: 60

  product_db_pool_properties:
    time_between_eviction_runs_millis: 3000000
    max_active: 10
    max_idle: 1
    initial_size: 1
    min_idle: 1
    max_wait: 10000
    remove_abandonded_timeout: 60

snmp:
  cache_pool_properties:
  max_total: 10
  max_idle: 5
  min_idle: 2
  num_tests_per_eviction_run: 5
  time_between_eviction_runs_millis: 60000
  cache_expire: 86400

mirwais:
  host: localhost
  env_name: cache_env_name

webtelemetry:
  url: "https://customer-prod-webtelemetry.example.com"
  base_url: "{{ webtelemetry_url }}/api/telemetrix"

internal_api:
  user: internal_api_user
  pass: reduce

ssn_amm:
  user: ssn_amm_user
  pass: ssn_amm_pass
  url:  https://ssnagent.example.net:6875/agent/amm/v2_0/

ssn_hcm:
  user: ssn_hcm_user
  pass: ssn_hcm_pass
  url: https://ssnagent.example.net:6875/agent/hcm/v1_6/

#other
nagios:
  checks:
    - name: os
    - name: tomcat