require 'bundler/setup'
require 'bundler/gem_tasks'

task :release do
    raise 'You cannot release this in public'
end

require 'yard'
require 'yard/rake/yardoc_task'
YARD::Rake::YardocTask.new(:doc)
