# task to set host facts:
#   - Java is installed?
#   - which Java version is installed?

# determine if Java is already installed
- name: RedHat | register oracle_java_installed
  shell: "which java"
  register: oracle_java_task_installed
  ignore_errors: yes
  changed_when: False
# oracle_java_installed.rc == 0 : installed
# oracle_java_installed.rc == 1 : not installed

- name: RedHat | echo oracle_java_task_installed
  debug:
    msg="oracle_java_task_installed={{ oracle_java_task_installed }}"
  when: oracle_java_task_installed is defined
  tags:
    - debug

- name: RedHat | set fact oracle_java_installed
  set_fact:
    oracle_java_installed={{ oracle_java_task_installed.rc == 0 }}
  changed_when: False

- name: RedHat | echo oracle_java_installed
  debug:
    msg="oracle_java_installed={{ oracle_java_installed }}"
  when: oracle_java_installed is defined
  tags:
    - debug

# determine which Java version is installed

- name: RedHat | if Java is installed, check version
  shell: java -version 2>&1 | head -n 1 | awk '{ print $3 }' | awk -F '"' '{ print $2 }'
  when: oracle_java_installed
  register: oracle_java_task_version
  changed_when: False

- name: RedHat | echo oracle_java_task_version
  debug:
    msg="oracle_java_task_version={{ oracle_java_task_version }}"
  when: oracle_java_task_version is defined
  tags:
    - debug

- name: RedHat | set fact oracle_java_installed_version
  set_fact:
    oracle_java_version_installed={{ oracle_java_task_version.stdout }}
  when: oracle_java_installed
  changed_when: False

- name: RedHat | echo oracle_java_version_installed
  debug:
    msg="oracle_java_version_installed={{ oracle_java_version_installed }}"
  when: oracle_java_version_installed is defined
  tags:
    - debug

- name: RedHat | echo oracle_java_version_string
  debug:
    msg="oracle_java_version_string={{ oracle_java_version_string }}"
  when: oracle_java_version_string is defined
  tags:
    - debug

# Task file to install Oracle Java Development Kit in a system with a Redhat based Linux distribution.
#

- name: RedHat | download Java RPM
  shell:
    "curl -L  -H 'Cookie:oraclelicense=accept-securebackup-cookie' -o {{ oracle_java_dir_source }}/{{ oracle_java_rpm_filename }} {{ oracle_java_rpm_url }}"
  args:
    creates: "{{ oracle_java_dir_source }}/{{ oracle_java_rpm_filename }}"
  register: oracle_java_task_rpm_download
  become: yes
  tags:
    - installation

- name: RedHat | install RPM
  yum:
    name="{{ oracle_java_dir_source }}/{{ oracle_java_rpm_filename }}"
    state=present
  when: not oracle_java_task_rpm_download|skipped
  become: yes
  tags:
    - installation

- name: RedHat | set Java version as default
  alternatives:
    name="{{ item.exe }}"
    link="/usr/bin/{{ item.exe }}"
    path="{{ item.path }}/{{ item.exe }}"
  when: oracle_java_set_as_default
  with_items:
    - { path: "{{ oracle_java_home }}/jre/bin", exe: 'java' }
    - { path: "{{ oracle_java_home }}/jre/bin", exe: 'keytool' }
    - { path: "{{ oracle_java_home }}/bin", exe: 'javac' }
    - { path: "{{ oracle_java_home }}/bin", exe: 'javadoc' }
  become: yes
  when: oracle_java_task_rpm_download|changed or (oracle_java_installed and oracle_java_version_installed != oracle_java_version_string)
  register: oracle_java_task_set_default

#- name: in case there were changes, check host environment again
  #include: ../check_environment.yml
#  when: not oracle_java_task_rpm_download|skipped or oracle_java_task_set_default|changed
