---

galaxy_info:
  author: Jiri Tyr
  description: Role to install and configure Grafana
  license: MIT
  min_ansible_version: 1.9
  platforms:
    - name: EL
      versions:
        - all
  categories:
    - system
dependencies: []
