#role: wt_go
#task: recreate POSTGRESQL views
---

- name: Recreate the POSTGRESQL views table
  shell: "/home/{{ influxdb.user }}/.rbenv/shims/bundle exec rake db:views:reset APP_ENV={{ influxdb.rails_env }}"
  args:
    chdir: "{{ influxdb.path }}"
  environment:
    APP_KEY: "{{ app_environment.APP_KEY }}"
  sudo_user: "{{ influxdb.user }}"
  run_once: true

- name: Run SQL queries to recreate the POSTGRESQL views
  shell: "/home/{{ influxdb.user }}/.rbenv/shims/bundle exec rake db:views:populate APP_ENV={{ influxdb.rails_env }}"
  args:
    chdir: "{{ influxdb.path }}"
  environment:
    APP_KEY: "{{ app_environment.APP_KEY }}"
  sudo_user: "{{ influxdb.user }}"
  run_once: true

- pause: seconds=5
