#role: wt_go
#task: precompile_assets
---
- name: $ bundle exec rake bower:clean
  shell: "/home/{{ influxdb.user }}/.rbenv/shims/bundle exec rake bower:clean"
  args:
    chdir: "{{ influxdb.path }}"
  sudo_user: "{{ influxdb.user }}"

- name: $ bundle exec rake bower:install
  shell: "/home/{{ influxdb.user }}/.rbenv/shims/bundle exec rake bower:install"
  args:
    chdir: "{{ influxdb.path }}"
  sudo_user: "{{ influxdb.user }}"

- name: Precompile assets
  shell: "/home/{{ influxdb.user }}/.rbenv/shims/bundle exec rake assets:precompile APP_ENV={{ influxdb.rails_env }}"
  args:
    chdir: "{{ influxdb.path }}"
  environment:
    APP_KEY: "{{ app_environment.APP_KEY }}"
  sudo_user: "{{ influxdb.user }}"
