---
- name: Prepare installation
  include: prepare.yml
  tags: [ deploy ]

- name: Update repo
  include: go-get-repo.yml
  tags: [ update ]

- name: Bundler tasks
  include: bundle.yml
  tags: [ update ]

- name: Update configs
  include: update_configs.yml
  tags: [ configs ]

- name: Setup database
  include: setup_database.yml
  tags: [ setup ]

- name: Migrate the database
  include: migrate.yml
  tags: [ update ]

- name: Precompile assets
  include: go-get-assets.yml
  tags: [ update ]

- name: Rake tasks
  include: rake_tasks.yml
  tags: [ update ]

- name: POSTGRESQL Views
  include: db_views.yml
  tags: [ update ]

- name: Create services
  include: create_service.yml
  tags: service

- name: Restart services
  include: restart_service.yml
  tags: [ update, configs, service, restart ]
