#role: wt_go
#task: populate the ui_messages table
---

- name: Populate the database with UiMessag objects.
  shell: "/home/{{ influxdb.user }}/.rbenv/shims/bundle exec rake influxdb:seed_ui_messages APP_ENV={{ influxdb.rails_env }}"
  args:
    chdir: "{{ influxdb.path }}"
  environment:
    APP_KEY: "{{ app_environment.APP_KEY }}"
  sudo_user: "{{ influxdb.user }}"
  run_once: true

- name: Populate database with ResultsFeature objects.
  shell: "/home/{{ influxdb.user }}/.rbenv/shims/bundle exec rake influxdb:seed_results_features APP_ENV={{ influxdb.rails_env }}"
  args:
    chdir: "{{ influxdb.path }}"
  environment:
    APP_KEY: "{{ app_environment.APP_KEY }}"
  sudo_user: "{{ influxdb.user }}"
  run_once: true
