# Deploy wildrivertechnologies.com wildcart cert

required_roles:  [ core_web ]


tasks:
    - files
    - run_commands:make_ssl_links

files:
  /usr/local/ssl/certs/wildrivertechnologies.com.crt:
    source: webtelemetry-dev/wildrivertechnologies.com.crt
        owner:  root
        group:  root
        mode:  0644
  /usr/local/ssl/private/wildrivertechnologies.com.key:
    source: webtelemetry-dev/wildrivertechnologies.com.key
        owner:  root
        group:  root
        mode:  0600


run_commands:
    make_ssl_links:
    - [ root, /usr/local/ssl/certs, 'ln -s wildrivertechnologies.com.crt webtelemetry_star.crt' ]
    - [ root, /usr/local/ssl/private, 'ln -s wildrivertechnologies.com.key webtelemetry_star.key' ]
