required_roles:  [ core_web ]


tasks:
    - run_commands:get_sslcerts
    - run_commands:make_ssl_links


run_commands:
    get_sslcerts:
        - [ root, /usr/local/ssl/certs,
            'curl -u ai:AGdev0ps -O http://10.0.0.11/sslcerts/wildrivertechnologies.com/wildrivertechnologies.com.ca-chain.crt' ]
        - [ root, /usr/local/ssl/certs,
            'curl -u ai:AGdev0ps -O http://10.0.0.11/sslcerts/wildrivertechnologies.com/wildrivertechnologies.com.crt' ]
        - [ root, /usr/local/ssl/private,
            'curl -u ai:AGdev0ps -O http://10.0.0.11/sslcerts/wildrivertechnologies.com/wildrivertechnologies.com.key' ]
        - [ root, /usr/local/ssl/private, 'chmod 600 wildrivertechnologies.com.key' ]

    make_ssl_links:
    - [ root, /usr/local/ssl/certs, 'ln -s wildrivertechnologies.com.ca-chain.crt webtelemetry_star.crt']
    - [ root, /usr/local/ssl/private, 'ln -s wildrivertechnologies.com.key webtelemetry_star.key']

