---
cloudera_manager: true
cdh_version: 5
cdh_build: 5.7.1

hbase_mounts:
  - device_name: /dev/xvdh
    mount_point: /hbase/vol01
  - device_name: /dev/xvdi
    mount_point: /hbase/vol02
  - device_name: /dev/xvdj
    mount_point: /hbase/vol03
  - device_name: /dev/xvdk
    mount_point: /hbase/vol04
  - device_name: /dev/xvdl
    mount_point: /hbase/vol05
  - device_name: /dev/xvdm
    mount_point: /hbase/vol06
  - device_name: /dev/xvdn
    mount_point: /hbase/vol07
  - device_name: /dev/xvdo
    mount_point: /hbase/vol08
  - device_name: /dev/xvdp
    mount_point: /hbase/vol09
  - device_name: /dev/xvdr
    mount_point: /hbase/vol10

## limits.conf settings ##

limits_lines:
  - "hdfs  -       nofile  32768"
  - "hbase -       nofile  32768"

telemetrix:
  logger:
    logdir: /WT/logs
