
# These Company groups will always be checked and created #
groups:
    - wtuser
    - wtadmin
    - dev
    - ops
    - telemetrix


# Deploy user_& groups configs
user_groups:
    ops:  [ gordon, armand, samuel, gabriel, leoshatokhin ]
    dev:     [ armand, leoshatokhin, matt.olson, alexpennanen, vishal ]
    wtuser :     [ sergey, kamil, mcho, ruslan, ]
    wtadmin:
    telemetrix:  [ rahul, viridiana, brian, tommy ]

# Individual User settings #
users:
    defaults:
        group: wtgroup
        shell: /bin/bash
        source_profile:
            - /WT/profiles/profile-webtelemetry_core.sh
        create_gitconfig:  yes
        create_bash_profile:  yes

    gordon.cavendish:
        groups: [ dev, wtadmin ]
        comment: Gordon Cavendish
        emdevl: gordon@webtelemetry.us
        pubkey:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCa6vMdevRZCksXpTH4Hb3LfCH3LqMiOsv7cgNytwFsZpXbrIE0acobKTUlmobMeYDJEgJcDPKR8l64aye3NTDhphlY5jGLYHkAKh3oTsYjXpzw/4+fUFFGa0y12SZA6JRUTe3UgLmXsw1thhJVNJV4yDDWUXA0359jplFg0BryCQfRYRg2QxyY227pwiKCmorodpdih5fLa8xMJysfEZnd+P6789aGj/m4sbi2UYxaf1xj9EtCtD0GtH/comtKAV6i7K/dHIEZyx9wplnysw4Fj/JttTNLDCN15O5mOJwSx/WgIKimVyePOQ6JiAjbmc+mHAhw1b5BAeRg7fNb1ZJ8h gordon@webtelemetry.us
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCWFH4D3vIUdiVOqP210+52CxiaYzGLB/osI86zT9kvzNjtqlNXs1vQ+ozKw7LchbMzi2KNqOdpqg0qLpRvgltyyihYaHGsswVDFel8R76Ga0/EoGomGgKQ90qUZHKRNi18YFmOgEMSSVQVToEcvQrYxIANRO6f5Gfs6In+D9M5GV5/ZYKgY6bK0dGIdfSuVdjKpFnZqJBxX+vl5C7u1Q8LEfkGO17qvW+WU3kb/atuE7QvMS46sZlFTuydgW1JRoMwoQr/jaPc2GmL2xTQyxfhRV64PQ5Ki6VdGSGan3bqXjeP7yr5rgQZBo/ek5n2k1Bu6CnIRh8DggESjSwdlEC7 gordon@webtelemetry.us

    armand.scaramucci:
        groups: [ dev, wtadmin ]
        comment: Armand Scaramucci
        emdevl: armand.scaramucci@webtelemetry.us
        pubkey:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGNMiBfOw/V61234woxfEBdGI8AhOuaezF8UmtMErgZ8BTjxRKOFkA2ERD2iZ/pXKkYtCH5vXBb6ia4suG6OAkA9bzYNECF1gV+TZE5Ibwc4Z+rBWA+iWOMgziMxEdNefi0E5l+Z2c9/ZQwmb8upARYroHrnp6V4xohDLhbdJyrkN7PtoxlnYmZyhK3s4H1mzVRFyNyZcBqpfUlbkjRWygrZH3V/vGvUynt8ZMd+i3+aYS0xP+nWavCEx4K+5VCpqvvCVeUsha/RANw8CCQmSXFu9sBgAQke+rZbW2qzWGxLvaeQjLw6C1P6ziW1rFe3LZAswjFG7WTs45aBjtdCLB GitHub@austinAG

    viridiana.lourdes:
        groups: [ {{ viridiana.lourdes }} ]
        comment:  Viridiana Lourdes
        emdevl:  viridiana.lourdes@webtelemetry.us
        pubkey:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC1VzA+0CTEBBIgEdygAMZo2Geu49ENHmgQb2Z3X8IViY9pun149y29Yos/qO2NoiOin9da5Qv3wEDfuorh4gAPpBhvJ+UoA97zXIOA4A1tJSdr7ktc1kQraDtNMFD58xcy4ET/pWIG9ST/gVWef/EqY/wSNBeCV567ZaZpmERe2Dczi/QGMpV0nmftbIvV4DUYcRrlD3o48BJmUT5tHDc8+UVIlN/piM9ls01f/v0bIB9Qy/UpsnR/wcuOnUlb9BjE7zshkL2BuIgIi0j74Z4AQvdA4tfhS6x5/cUPF1EzFnXkFjqE5Bzvb0PY6MG2FXkr/Qgg9hqQlU84KcPU7YA7ShtqDCIKTApyfIoa4Y8j4PniABgxCcWD6rD+3lqsRuVOe7dkistrjkzFKbLCFBVE5CUiqSNvS1VDufkqsu3Ok+OhxtkhuN1S8TTSdbV1x4L7j+E516Fel74UMFIVo1PSfTepUNaS2mg+ZVJQ6z9cyEAtRPyQ7UpyZZiBvYjaLQ3qDwvJyd3Q3wsOC3Q41xV9eCVD8GYIo7uiuh1EYuvmKg1n0vHd52zGIzNkplLgUfIMJfdXz2mhUyM29FWQZfBIHbDbqLXbcde/B5BmuDzsAOE5ky4Lir3fsY8qa3iil6lWE7TH7aHH0TgiKRfNdTh6qHzOK/DL3NkSXlBlWWBBGQ== viridiana@Viridianas-MacBook-Pro.local

    mark.chew:
        groups: [ {{ mark.chew }} ]
        comment: Mark Chew
        emdevl: mark.chew@webtelemetry.us
        pubkey:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDVSp52+6j47pUb/yL2HR7egkwKDzS+fzHeAC3IG9NZWFb7s/6O4HS2ojb/qju0lLf/y2P2PWkAhYGlF3Ek5Db2s9rMKZAtS9ymmFbx3jQtrQW5M4Hbgd3EfEm0oowPWbkviGUgsOLBcrQHtpYAns7PMBZvWKYfjGmJiGLvq5c2SJTA2r67B/Zn3nFXmwiAeOJ1CDdBQRYMpxH7VvE6E8k+Lile11jw4TSbg1RS+xq6rQyqr0UxGEIHgAIGENKqMeyfS6pumHOlK7zF5zvGbK9cbBNufPO0tR7kSZLzbpIA1xcxx/uVPrHeKYhvpN8xOWxINGQVrna9SX+TzNxHNxeZjc/mkB4+5XavmqTNRFy0qSlB5AtRnNRMTFdjmbSGmbcucQ5GQpGxhPRi2x1UfdEQKzn76WCV6POUWDRiZk82cP7qVpHk+9p9aUKwGdA/2ezylDgw1hRmFetXYOLMpY/ec6+fWwWQhBDZihDiEmpW1jVkAsGzHhiHAKz2KKAYO1L5Ag7yi8KmG/UbOnyRxxQ2k1h2E9WCuVCgy5pusA4lseozofSzofcKQH5AzbKUqpAuvSOqUAFMYrqq+V0bP1jeDKrmCrz6KrczO9HXExdPoy6slkWGjDdrH/BNmHwbJnru+Ij08Ju3Y4UGjOAgKwi4wfXCNv7JuXvXsQizaNskfQ== mark.chew@Mark-Chew.local

    quentin.sanders:
        groups: [ wtadmin ]
        comment: Quentin Sanders
        emdevl:  quentin.sanders@webtelemetry.us
        pubkey:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNjX8koQJhq4lVNNblB/2ia8QQhG27lQlArr2FWdU1oBtkAaV7bt16iCe2b2Sy76/lo6vyGiqEZFqhchMY81ppzjDb5rO57t9UT4dDaTHrrt1FuffPYIz8UnBNCKMAe2dKh18nY8l3CSnJi0FrHc7Qtcxsk6Ai3G9kLFFZq0CtodEOliE7IcOyxYxIJHLnouBmUNB+CoNQplNQ3T3orFHIBpJA8xYl4RWH9/aQW9Kx9DuJwJ9etAKUxZM90+LIch7k/CdmMCjQyclOt67oZxNtEYT4tA0rMDIzd3eErCWCi6T2i4OTjvhFhq/AOZ6AwvgSNb4e5X4jgtg/5idHKnYP quentin.sanders@webtelemetry.us

    samuel.hunsworth:
        groups: [ wtadmin ]
        comment: Samuel Hunsworth
        emdevl: samuel.hunsworth@webtelemetry.us
        pubkey:
            - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAx8IcZFlFgw60a0erEj/be9qbXKChuAasR04aLzhujWWo27tMt+Fvnm2I+cq2izIkeAi+OpFfnB8e2kPVJC1L5IZBZBMUcp+1BA44Y54j8CHwElQpj0NFrRUm8/BWJZ2MUIxfosvtw9nqN0SEL+BPDY04unaAM75dP1smkgceBM5H2Jqi/et4XzStwCfcJyJ7Jtu/BR0778A0TfvAOiecFkd2+PTKvHEZqF+TSjOscMrzHuwc6cfjlbE/NAk2IW1ZdQj9po+/eUEeu0U8Q9ffUIJ/aAfstXvXq/+bvbhdVtJuL7WGFGqqaD/bK/3Jlu2p4FIEhLGtepWBekSXKr0jZw== kamil@imac

    serega.bumer:
        groups: [ wtadmin ]
        comment: Serega Bumer
        emdevl: serega.bumer@webtelemetry.us
        pubkey:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgt5bFHu4OeVYB84FHfZzsm09H1ZoUqdAVXkt+ecRucc8XwN5AeyzlAsPHkMeeVT8tTsSKtli4C+pSa36l1xhoqxxWGFvbO2zo+EfyRmv5ODtEHpqZTgHg4lzaVamGoczhh1MS2GOXOHiae4ZawxvYpyWR7t933jqtz6VFFbi7bOpUs+RRMtoZJxaQTAv8hnCWn9t49Eg8i0M5xmXLSAyRBK0Eo5JG1H4NLxmWd46W3cJtv6QjKA8suVeot0T+cWTBiDcikqFmYp1M1fWUBQcOjfqNfAPbV3D+CUqe9an07DI6IePp0W4XqbapoIpadZNTL/lcFhfxx8ef4PD3dL71 sergey@ukstv.me

    gabriel.feinmann:
        groups: [ {{ gabriel.feinmann }} ]
        comment: Gabriel Feinmann
        emdevl: gabriel.feinmann@webtelemetry.us
        pubkey:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCyvuhr+0DJ+W3VqOt6RXJ/9Qot1okvsLU7kHYzCv8NWJvb+EAffWX8WFA+vL4p/LeaWM2Ek17nswPbNa1Q8gdR6yRjvp/Vu6/vCG6ms3XqIYkaKe4IXWkJbjWn22EapS7Rkn31LNPhuRfox31plqO81iSAHAJWmkpMgXHeWWGl5Ly7oj9SOdrs2C1gvbyXXZe6NvFlrllYw1nFeIdr/ZCDRG26vhxkWxBP5UfhqQ1hrXHZ3Y+H7dv1tK0B3AmW0JEtD1wxdhThgnRtT5r1quG4KVGKMlZ2oZZECamZeNbzSN/zUOIew03/P65xzB1nNOvsuG/7OPioOmTKnzmHgllv venkir@Venkateshs-MacBook-Pro.local