#role: wt_telemetrix
#task: bundle
---

- name: Gem install bundler
  shell: "/WT/.rbenv/shims/gem install bundler"
  sudo_user: "{{ grafana.user }}"

- name: Run rbenv rehash
  shell: "/home/{{ grafana.user }}/.rbenv/bin/rbenv rehash executable=/bin/bash chdir=/home/{{ grafana.user }}"
  sudo_user: "{{ grafana.user }}"

- name: Gem install bundle
  shell: "/home/{{ grafana.user }}/.rbenv/shims/gem install bundle"
  sudo_user: "{{ grafana.user }}"

- name: Run rbenv rehash
  shell: "/home/{{ grafana.user }}/.rbenv/bin/rbenv rehash executable=/bin/bash chdir=/home/{{ grafana.user }}"
  sudo_user: "{{ grafana.user }}"

- name: Install dependencies (bundle install)
  shell: "/home/{{ grafana.user }}/.rbenv/shims/bundle install"
  args:
    chdir: "{{ grafana.path }}"
    executable: /bin/bash
  sudo_user: "{{ grafana.user }}"

- name: Run rbenv rehash
  shell: "/home/{{ grafana.user }}/.rbenv/bin/rbenv rehash executable=/bin/bash chdir=/home/{{ grafana.user }}"
  sudo_user: "{{ grafana.user }}"