---
- name: Install python packages
  include: pip_install.yml

- name: Update configs
  include: update_configs.yml
  tags: [ configs ]

- name: Create services
  include: create_service.yml
  tags: [ configs ]

- name: Set up Nginx
  include: nginx.yml
  tags: [ configs, restart ]
  when: webserver.nginx

- name: Init DB
  include: init_rdb.yml
  tags: [ db ]
  when: rdbms.django is defined

- name: Restart services
  include: restart_service.yml
  tags: [ restart ]
