- name: APT update
  apt:
    update_cache: yes
    cache_valid_time: 3600
  register: apt_result
  until: apt_result|success
  retries: 3
  delay: 1
  ignore_errors: yes

- name: retry if needed using command apt-get update
  command: apt-get update
  when: apt_result|failed

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - unattended-upgrades

- name: Update unattended-upgrades config
  template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Update periodic config
  template:
    src: periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic
